#!/bin/bash
#funções
    function escolher_modo_replicação() {
        while true; do
            echo "Escolha o modo de replicação desejada:"
            echo "1. Síncrona"
            echo "2. Assíncrona"
            echo ""
            read -p "Digite a opção: " opcao
            #Verificador
            [[ $opcao =~^[1-2]$ ]] && break || echo "Opção invalida."
            done
        return $opcao
    }
    
    # Função para iniciar a replicação síncrona
    function iniciar_replicacao_sincro() {

        echo "Iniciando replicação síncrona..."
        systemctl start mysql
        #configurar
        echo "innodb_flush_log_at_trx_commit = 1" >> /etc/mysql/mysql.conf.d/mysqld.cnf
        echo "innodb_sync_binlog =1" /etc/mysql/mysql.conf.d/mysql.cnf
        #reiniciar
        systemctl restart mysql
        #verificar
        mysql -e "SHOW SLAVE STATUS\G" | grep "Slave_IO_State: Waiting for master to send event"
        echo "Replicação síncrona bem-sucedida" $? -eq 0 && "deu zica. Verifique os logs do MySQL."
    }

    # Função para iniciar a replicação assíncrona
    function iniciar_replicacao_assincrona() {
        echo "Iniciando replicação síncrona..."
        systemctl start mysql
        #configurar
        echo "innodb_flush_log_at_trx_commit = 0" >> /etc/mysql/mysql.conf.d/mysqld.cnf
        echo "innodb_sync_binlog =0" /etc/mysql/mysql.conf.d/mysql.cnf
        #reiniciar
        systemctl restart mysql
        #verificar
        mysql -e "SHOW SLAVE STATUS\G" | grep "Slave_IO_State: Waiting for master to send event"
        echo "Replicação assíncrona bem-sucedida" $? -eq 0 && "deu zica. Verifique os logs do MySQL."
    }

#Chamada
    if [ $modo_replicacao -eq 1 ]; then
        iniciar_replicacao_sincro
    elif [ $modo_replicacao -eq 2 ]; then
        iniciar_replicacao_assincrona
    fi
    echo "Replicação iniciada no modo $((modo_replicacao == 1 ? "sincrono" : "assíncrono"))."
